<?php $item = $item ?? []; $days = [1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu']; ?>
<div class="card bg-white rounded-10 border border-white mb-4"><div class="p-20 border-bottom"><h4 class="erp-detail-section-title mb-0">Informasi Jadwal</h4></div><div class="p-20 row g-4">
    <div class="col-md-4"><label class="erp-detail-label">Dokter</label><select class="form-control" name="doctor_id" required><?php foreach ($doctors as $doctor): ?><option value="<?= $doctor['id'] ?>" <?= (int)($item['doctor_id'] ?? 0) === (int)$doctor['id'] ? 'selected' : '' ?>><?= htmlspecialchars($doctor['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="erp-detail-label">Poli</label><select class="form-control" name="polyclinic_id" required><?php foreach ($polyclinics as $poly): ?><option value="<?= $poly['id'] ?>" <?= (int)($item['polyclinic_id'] ?? 0) === (int)$poly['id'] ? 'selected' : '' ?>><?= htmlspecialchars($poly['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="erp-detail-label">Hari</label><select class="form-control" name="day_of_week"><?php foreach ($days as $num => $day): ?><option value="<?= $num ?>" <?= (int)($item['day_of_week'] ?? 1) === $num ? 'selected' : '' ?>><?= $day ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="erp-detail-label">Mulai</label><input type="time" class="form-control" name="start_time" value="<?= htmlspecialchars(substr($item['start_time'] ?? '08:00',0,5)) ?>"></div>
    <div class="col-md-3"><label class="erp-detail-label">Selesai</label><input type="time" class="form-control" name="end_time" value="<?= htmlspecialchars(substr($item['end_time'] ?? '12:00',0,5)) ?>"></div>
    <div class="col-md-3"><label class="erp-detail-label">Kuota</label><input type="number" class="form-control" name="quota" value="<?= htmlspecialchars($item['quota'] ?? 20) ?>"></div>
    <div class="col-md-3"><label class="erp-detail-label">Status</label><select class="form-control" name="status"><option value="active" <?= ($item['status'] ?? 'active') === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= ($item['status'] ?? '') === 'inactive' ? 'selected' : '' ?>>Inactive</option></select></div>
</div></div>
