<?php $days = [1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu']; ?>
<div class="card bg-white rounded-10 border border-white mb-4">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 p-20"><div><h3 class="mb-0">Jadwal Dokter</h3><p class="text-body fs-14 mb-0">Mapping dokter, poli, hari, jam, dan kuota.</p></div><a href="<?= url('simrs-doctor-schedules-create') ?>" class="btn btn-primary text-white erp-btn">+ Tambah Jadwal</a></div>
    <div class="p-20 border-top"><form class="row g-2"><input type="hidden" name="page" value="simrs-doctor-schedules"><div class="col-md-10"><input class="form-control" name="search" value="<?= htmlspecialchars($search ?? '') ?>" placeholder="Cari dokter/poli"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Cari</button></div></form></div>
    <div class="default-table-area mx-minus-1"><div class="table-responsive"><table class="table"><thead><tr><th>Dokter</th><th>Poli</th><th>Hari</th><th>Jam</th><th>Kuota</th><th>Status</th></tr></thead><tbody>
    <?php foreach ($items as $item): ?><tr><td><a class="text-primary fw-semibold" href="<?= url('simrs-doctor-schedules-edit', ['id' => $item['id']]) ?>"><?= htmlspecialchars($item['doctor_name'] ?? '-') ?></a><br><small><?= htmlspecialchars($item['specialist'] ?? '') ?></small></td><td><?= htmlspecialchars($item['polyclinic_name'] ?? '-') ?></td><td><?= $days[(int)$item['day_of_week']] ?? '-' ?></td><td><?= substr($item['start_time'],0,5) ?> - <?= substr($item['end_time'],0,5) ?></td><td><?= (int)$item['quota'] ?></td><td><?= simrsStatusBadge($item['status'] ?? '') ?></td></tr><?php endforeach; ?>
    <?php if (empty($items)): ?><tr><td colspan="6" class="text-center py-4">Belum ada jadwal.</td></tr><?php endif; ?>
    </tbody></table></div><?= adminListFooter($baseRoute ?? 'simrs-doctor-schedules', $search ?? '', $currentPage ?? 1, $totalPages ?? 1, $totalData ?? count($items ?? []), $limit ?? 15) ?></div>
</div>
