<?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?= htmlspecialchars($_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
<?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?= htmlspecialchars($_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
<div class="card bg-white rounded-10 border border-white mb-4">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3 p-20"><div><h3 class="mb-0">Pendaftaran Pasien</h3><p class="text-body fs-14 mb-0">Daftar kunjungan rawat jalan dan antrean hari ini.</p></div><a href="<?= url('simrs-registration-create') ?>" class="btn btn-primary text-white erp-btn">+ Daftar Kunjungan</a></div>
    <div class="p-20 border-top"><form class="row g-2"><input type="hidden" name="page" value="simrs-registration"><div class="col-md-10"><input class="form-control" name="search" value="<?= htmlspecialchars($search ?? '') ?>" placeholder="Cari kunjungan/pasien"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Cari</button></div></form></div>
    <div class="default-table-area mx-minus-1"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Kunjungan</th><th>Pasien</th><th>Poli / Dokter</th><th>Antrean</th><th>Status</th></tr></thead><tbody>
    <?php foreach ($visits as $visit): ?><tr><td><?= htmlspecialchars($visit['visit_no']) ?><br><small><?= htmlspecialchars($visit['visit_date']) ?></small></td><td><?= htmlspecialchars($visit['patient_name']) ?><br><small><?= htmlspecialchars($visit['medical_record_no']) ?></small></td><td><?= htmlspecialchars($visit['polyclinic_name']) ?><br><small><?= htmlspecialchars($visit['doctor_name'] ?: '-') ?></small></td><td class="fw-bold"><?= htmlspecialchars($visit['queue_no'] ?: '-') ?></td><td><?= simrsStatusBadge($visit['status'] ?? '') ?></td></tr><?php endforeach; ?>
    <?php if (empty($visits)): ?><tr><td colspan="5" class="text-center py-4">Belum ada pendaftaran hari ini.</td></tr><?php endif; ?>
    </tbody></table></div><?= adminListFooter($baseRoute ?? 'simrs-registration', $search ?? '', $currentPage ?? 1, $totalPages ?? 1, $totalData ?? count($visits ?? []), $limit ?? 10) ?></div>
</div>
